services:
  db:
    image: pgvector/pgvector:pg17
    container_name: rosetta-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rosetta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rosetta_password
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rosetta" ]
      interval: 5s
      timeout: 5s
      retries: 5
