"""
Organize LLM-generated documentation into a single folder.

This script:
1. Creates a .llm-docs/ directory
2. Moves all LLM-generated markdown files there
3. Updates .gitignore to exclude this directory
"""
import os
import sys
import shutil
from pathlib import Path

# Set UTF-8 encoding for console output on Windows
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# LLM-generated docs in root directory (excluding README.md which is user-maintained)
ROOT_LLM_DOCS = [
    "CATALOG_FIX_APPLIED.md",
    "CLEANUP_SUMMARY.md",
    "HOW_TO_RUN.md",
    "IMPROVEMENTS_SUMMARY.md",
    "MIGRATION_SCHEMA_ISSUES.md",
    "MIGRATION_STATUS.md",
    "POSTGRESQL_INTEGRATION.md",
    "POSTGRES_MIGRATION_QUICKSTART.md",
    "QUICK_REFERENCE.md",
    "QUICK_START_MEANING_EDITOR.md",
    "RECENT_IMPROVEMENTS.md",
    "SCHEMA_FIX_APPLIED.md",
    "SUMMARY_OF_IMPROVEMENTS.md",
]

# LLM-generated docs in docs/ directory
DOCS_LLM_DOCS = [
    "docs/BOOK_VALIDATION_GUIDE.md",
    "docs/MEANING_EDITOR_GUIDE.md",
    "docs/MIGRATION_GUIDE.md",
    "docs/POLYSEMY_EXAMPLES.md",
    "docs/POSTGRESQL_MIGRATION_COMPLETE.md",
    "docs/POSTGRESQL_SETUP.md",
    "docs/SEARCH_FEATURE_GUIDE.md",
    "docs/SENSE_CLUSTERING_IMPROVEMENTS.md",
    "docs/WORD_EXTRACTION_STRATEGY.md",
]

def main():
    # Create .llm-docs directory
    llm_docs_dir = Path(".llm-docs")
    llm_docs_dir.mkdir(exist_ok=True)
    print(f"✅ Created directory: {llm_docs_dir}/\n")

    moved_count = 0
    skipped_count = 0

    # Move root-level docs
    print("Moving root-level documentation:")
    print("-" * 80)
    for doc in ROOT_LLM_DOCS:
        src = Path(doc)
        if src.exists():
            dst = llm_docs_dir / doc
            shutil.move(str(src), str(dst))
            print(f"  ✅ Moved: {doc} → .llm-docs/{doc}")
            moved_count += 1
        else:
            print(f"  ⏭️  Skip: {doc} (not found)")
            skipped_count += 1

    # Move docs/ directory files
    print("\nMoving docs/ directory documentation:")
    print("-" * 80)
    docs_subdir = llm_docs_dir / "guides"
    docs_subdir.mkdir(exist_ok=True)

    for doc in DOCS_LLM_DOCS:
        src = Path(doc)
        if src.exists():
            dst = docs_subdir / src.name
            shutil.move(str(src), str(dst))
            print(f"  ✅ Moved: {doc} → .llm-docs/guides/{src.name}")
            moved_count += 1
        else:
            print(f"  ⏭️  Skip: {doc} (not found)")
            skipped_count += 1

    # Update .gitignore
    print("\nUpdating .gitignore:")
    print("-" * 80)
    gitignore_path = Path(".gitignore")

    # Read current .gitignore
    if gitignore_path.exists():
        with open(gitignore_path, "r", encoding="utf-8") as f:
            gitignore_content = f.read()
    else:
        gitignore_content = ""

    # Check if .llm-docs is already in .gitignore
    if ".llm-docs/" in gitignore_content or ".llm-docs" in gitignore_content:
        print("  ⏭️  .llm-docs/ already in .gitignore")
    else:
        # Add .llm-docs to .gitignore
        if not gitignore_content.endswith("\n"):
            gitignore_content += "\n"

        gitignore_content += "\n# LLM-generated documentation (Claude Code)\n"
        gitignore_content += ".llm-docs/\n"

        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write(gitignore_content)

        print("  ✅ Added .llm-docs/ to .gitignore")

    # Create index file
    print("\nCreating index file:")
    print("-" * 80)
    index_content = """# LLM-Generated Documentation

This directory contains documentation automatically generated by Claude Code during development sessions.

## Structure

### Root Level
Documentation about major features, migrations, and improvements:

"""

    for doc in sorted(ROOT_LLM_DOCS):
        doc_path = llm_docs_dir / doc
        if doc_path.exists():
            index_content += f"- [{doc}](./{doc})\n"

    index_content += """
### Guides (`guides/`)
Detailed guides and feature documentation:

"""

    for doc in sorted(DOCS_LLM_DOCS):
        doc_name = Path(doc).name
        doc_path = docs_subdir / doc_name
        if doc_path.exists():
            index_content += f"- [{doc_name}](./guides/{doc_name})\n"

    index_content += """
## Notes

- This directory is excluded from version control (see `.gitignore`)
- Files here are regenerated/updated during Claude Code sessions
- For permanent project documentation, use the main `README.md`
"""

    index_path = llm_docs_dir / "README.md"
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)

    print(f"  ✅ Created index: .llm-docs/README.md")

    # Summary
    print("\n" + "=" * 80)
    print("Summary:")
    print(f"  📦 Moved: {moved_count} files")
    print(f"  ⏭️  Skipped: {skipped_count} files (not found)")
    print(f"  📁 Created: .llm-docs/ directory")
    print(f"  🚫 Updated: .gitignore")
    print("=" * 80)
    print("\n✅ Documentation organized successfully!")
    print(f"\n📖 View the index: .llm-docs/README.md")

if __name__ == "__main__":
    main()
